version: '1.0.0-alpha-{build}'

before_build:
  - nuget restore

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

branches:
  only:
    - master

configuration: Release

build:
  verbosity: minimal

cache:
  - packages -> **\packages.config

deploy:
  provider: NuGet
  api_key:
    secure: jfcUvHZhgnUboplqTBDWr8mG5PIlrgBv5TA2fhhop4ZSiDxskyy+RtYyeHoduJFR