version: '{build}'

before_build:
  - nuget restore

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}.0.0"
  assembly_file_version: "{version}.0.0"
  assembly_informational_version: "{version}"