
version: '1.{build}.0-dev'
configuration: Release

branches:
  except:
    - master

pull_requests:
  do_not_increment_build_number: true

environment:
  apiKey:
    secure: F92kP6Fl41Uv4yoGN/PBsGKVPAkFIkvcBfQwFV2TCGyg1zihi7PD+BOSOUDfHkLg

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://gist.githubusercontent.com/PureKrome/0f79e25693d574807939/raw/8cf3160c9516ef1f4effc825c0a44acc918a0b5a/appveyor-build-info.ps'))

before_build:
  - nuget restore

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  parallel: true
  verbosity: minimal

on_success:
  - ps: if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { & ".\NuGet\NuGet Package and Publish.ps1" -Version $env:appveyor_build_version -NuGet "C:\Tools\NuGet\nuget.exe" -feedSource https://www.myget.org/F/nlog-bugsnag/api/v2 -apiKey $env:apiKey }

cache:
  - packages -> **\packages.config