
version: '1.{build}.0'
configuration: Release

branches:
  except:
    - master

pull_requests:
  do_not_increment_build_number: true

before_build:
  - nuget restore

build:
  parallel: true
  verbosity: minimal

cache:
  - packages -> **\packages.config